export const SET_CURRENT_USER = "APP/CURRENT_USER";
export const SET_LOADER = "APP/SET_LOADER";
export const SET_LOADER_DELETE = "SAVED-MOVIES/SET_LOADER_DELETE";
export const SET_LOGIN = "APP/SET_LOGIN ";
export const SET_FILTERED_MOVIES = "MOVIES/SET_FILTERED_MOVIES";
export const SET_SAVED_MOVIES = "MOVIES/SET_SAVED_MOVIES";
