const initialCards = [
  {
    link: "https://i.postimg.cc/bssm12PB/1.png",
    name: "33 слова о дизайне",
    duration: "1ч42м",
    owner: 1111,
    likes: [111],
  },
  {
    link: "https://i.postimg.cc/jSdmsLpN/2.png",
    name: "Киноальманах «100 лет дизайна»",
    duration: "1ч42м",
    owner: 1111,
    likes: [333],
  },
  {
    link: "https://i.postimg.cc/BnYytJ3z/3.png",
    name: "Бенкси",
    duration: "1ч42м",
    owner: 1111,
    likes: [1111],
  },
  {
    link: "https://i.postimg.cc/q7W5XQzX/4.png",
    name: "Баския: Взрыв реальности",
    duration: "1ч42м",
    owner: 1111,
    likes: [222],
  },
  {
    link: "https://i.postimg.cc/hGXYdNPt/5.png",
    name: "Бег это свобода",
    duration: "1ч42м",
    owner: 1111,
    likes: [222],
  },
  {
    link: "https://i.postimg.cc/Hx5PS5MG/6.jpg",
    name: "Бег это свобода",
    duration: "1ч42м",
    owner: 1111,
    likes: [222, 333],
  },
  {
    link: "https://i.postimg.cc/nrJSNzKX/7.png",
    name: "Бег это свобода",
    duration: "1ч42м",
    owner: 1111,
    likes: [111],
  },
  {
    link: "https://i.postimg.cc/NFkCtcbp/8.png",
    name: "Бег это свобода",
    duration: "1ч42м",
    owner: 1111,
    likes: [111],
  },
  {
    link: "https://i.postimg.cc/RC7DK79K/9.png",
    name: "Бег это свобода",
    duration: "1ч42м",
    owner: 1111,
    likes: [111],
  },
  {
    link: "https://i.postimg.cc/Dy7YgSyD/10.png",
    name: "Бег это свобода",
    duration: "1ч42м",
    owner: 1111,
    likes: [1111],
  },
  {
    link: "https://i.postimg.cc/m2Vp6TPr/11.png",
    name: "Бег это свобода",
    duration: "1ч42м",
    owner: 1111,
    likes: [1111],
  },
  {
    link: "https://i.postimg.cc/NjMJ3ZXk/12.png",
    name: "Бег это свобода",
    duration: "1ч42м",
    owner: 1111,
    likes: [1111],
  },
  {
    link: "https://i.postimg.cc/bwBCpLHc/13.png",
    name: "Бег это свобода",
    duration: "1ч42м",
    owner: 1111,
    likes: [1111],
  },
  {
    link: "https://i.postimg.cc/XvB2JFQZ/14.png",
    name: "Бег это свобода",
    duration: "1ч42м",
    owner: 1111,
    likes: [1111],
  },
  {
    link: "https://i.postimg.cc/9M3LqMnL/15.png",
    name: "Бег это свобода",
    duration: "1ч42м",
    owner: 1111,
    likes: [1111],
  },
  {
    link: "https://i.postimg.cc/3RgnjhMY/16.png",
    name: "Бег это свобода",
    duration: "1ч42м",
    owner: 1111,
    likes: [1111],
  },
];

const savedCards = [
  {
    link: "https://i.postimg.cc/q7W5XQzX/4.png",
    name: "Баския: Взрыв реальности",
    duration: "1ч42м",
    owner: 1111,
    likes: [111],
  },
  {
    link: "https://i.postimg.cc/NFkCtcbp/8.png",
    name: "Бег это свобода",
    duration: "1ч42м",
    owner: 1111,
    likes: [111],
  },
  {
    link: "https://i.postimg.cc/9M3LqMnL/15.png",
    name: "Бег это свобода",
    duration: "1ч42м",
    owner: 1111,
    likes: [111],
  },
];

module.exports = { initialCards, savedCards };
